# -*- coding: utf-8 -*-
"""6th__semester.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kAt7vHvMvcGB08cP7WKcSs4X6INlxr9n
"""

# app.py

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import plotly.io as pio
import random
from io import BytesIO

# Set Streamlit page configuration
st.set_page_config(
    page_title="Student Timetable Viewer",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Custom CSS for background image and additional styling
def add_bg_from_url():
    # Replace the URL below with your desired Taylor Swift image URL
    background_image_url = "https://i.imgur.com/your_image.jpg"  # Replace with your image URL
    st.markdown(
        f"""
        <style>
        .stApp {{
            background-image: url("{background_image_url}");
            background-attachment: fixed;
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
        }}
        /* Style for the download button */
        .download-button button {{
            background-color: #6a11cb;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
        }}
        .download-button button:hover {{
            background-color: #2575fc;
        }}
        </style>
        """,
        unsafe_allow_html=True
    )

add_bg_from_url()

# Sidebar for theme selection
st.sidebar.title("Settings")

# Define multiple color schemes
color_schemes = [
    {
        'name': 'Turquoise',
        'header_fill': '#1abc9c',
        'header_text': 'white',
        'time_fill': '#16a085',
        'time_text': 'white',
        'day_fill_1': '#ecf0f1',
        'day_fill_2': '#bdc3c7',
        'day_text': '#2c3e50'
    },
    {
        'name': 'Alizarin',
        'header_fill': '#e74c3c',
        'header_text': 'white',
        'time_fill': '#c0392b',
        'time_text': 'white',
        'day_fill_1': '#fdfefe',
        'day_fill_2': '#dfe6e9',
        'day_text': '#2d3436'
    },
    {
        'name': 'Wisteria',
        'header_fill': '#8e44ad',
        'header_text': 'white',
        'time_fill': '#732d91',
        'time_text': 'white',
        'day_fill_1': '#f5f6f4',
        'day_fill_2': '#dcdde1',
        'day_text': '#2c3e50'
    },
    {
        'name': 'Belize Hole',
        'header_fill': '#2980b9',
        'header_text': 'white',
        'time_fill': '#1f618d',
        'time_text': 'white',
        'day_fill_1': '#f0f3f4',
        'day_fill_2': '#d1ccc0',
        'day_text': '#2c3e50'
    },
    {
        'name': 'Green Sea',
        'header_fill': '#27ae60',
        'header_text': 'white',
        'time_fill': '#1e8449',
        'time_text': 'white',
        'day_fill_1': '#f8f9fa',
        'day_fill_2': '#dfe6e9',
        'day_text': '#2c3e50'
    }
]

# Streamlit widget for theme selection
selected_theme_name = st.sidebar.selectbox(
    "Choose Color Scheme",
    [scheme['name'] for scheme in color_schemes],
    index=0
)

# Retrieve the selected color scheme
selected_scheme = next(scheme for scheme in color_schemes if scheme['name'] == selected_theme_name)

# Load the section, professional elective, and core section files from GitHub
def load_data(url):
    try:
        df = pd.read_csv(url)
        return df
    except Exception as e:
        st.error(f"Error loading data from {url}: {e}")
        return None

section_url = 'https://raw.githubusercontent.com/satyam26en/6th-Semester-TIME__TABLE/main/section_list_6Th_semester%20-%20Sheet1.csv'
elective_url = 'https://raw.githubusercontent.com/satyam26en/TIME_TABLE_KIIT/main/Professional_Elective%20-%20Sheet1.csv'
core_url = 'https://raw.githubusercontent.com/satyam26en/6th-Semester-TIME__TABLE/main/6th_core%20-%20Sheet1.csv'

# Load data
section_df = load_data(section_url)
elective_df = load_data(elective_url)
core_df = load_data(core_url)

# Check if data loaded successfully
if section_df is None or elective_df is None or core_df is None:
    st.stop()

# Normalize the 'Roll No.' column
section_df['Roll No.'] = section_df['Roll No.'].astype(str).str.strip()

# Define the order of days and times
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
times = ['8 TO 9', '9 TO 10', '10 TO 11', '11 TO 12', '12 TO 1', '1 TO 2', '2 TO 3', '3 TO 4', '4 TO 5']

# Define a mapping from abbreviated to full day names
day_mapping = {
    'MON': 'Monday',
    'TUE': 'Tuesday',
    'WED': 'Wednesday',
    'THU': 'Thursday',
    'FRI': 'Friday',
    'SAT': 'Saturday'
}

# Function to standardize time slot names
def standardize_time_slot(time_slot):
    time_slot_mapping = {
        '8 TO 9': '8 TO 9',
        '9 TO 10': '9 TO 10',
        '10 TO 11': '10 TO 11',
        '11 TO 12': '11 TO 12',
        '12 TO 1': '12 TO 1',
        '1 TO 2': '1 TO 2',
        '2 TO 3': '2 TO 3',
        '3 TO 4': '3 TO 4',
        '4 TO 5': '4 TO 5'
    }
    # Remove extra spaces in the time slot string to match the mapping
    standardized_slot = ' '.join(time_slot.upper().split())
    return time_slot_mapping.get(standardized_slot, time_slot)

# Function to generate the timetable dataframe
def generate_timetable_df(roll_number):
    # Find the section details for the given roll number
    student_section = section_df[section_df['Roll No.'] == roll_number]

    if student_section.empty:
        st.error("Roll number not found.")
        return None

    # Extract the core section and elective sections
    core_section = student_section['Core Section'].values[0]
    elective_1_section = student_section['Professional Elective 1'].values[0]
    elective_2_section = student_section['Professional Elective 2'].values[0]

    # Retrieve the weekly timetable for Professional Electives 1 and 2
    elective_1_timetable = elective_df[elective_df['Section(DE)'] == elective_1_section]
    elective_2_timetable = elective_df[elective_df['Section(DE)'] == elective_2_section]
    core_timetable = core_df[core_df['Section'] == core_section]

    # Initialize the timetable matrix
    timetable_matrix = pd.DataFrame(index=times, columns=days, data='')

    # Function to fill the timetable matrix with subject names and room numbers
    def fill_timetable(timetable_df):
        room_columns = [col for col in timetable_df.columns if 'ROOM' in col]
        for index, row in timetable_df.iterrows():
            day = day_mapping.get(row['DAY'], 'Unknown')
            if day == 'Unknown':
                continue  # Skip if day is not in the mapping
            for col in room_columns:
                if row[col] != '---':
                    time_col_index = timetable_df.columns.get_loc(col) + 1
                    if time_col_index >= len(timetable_df.columns):
                        continue  # Prevent index out of range
                    time_col = timetable_df.columns[time_col_index]
                    time_slot = standardize_time_slot(time_col)
                    subject = row.get(time_col, 'N/A')
                    room_number = row[col]
                    if isinstance(subject, str) and subject.lower() != 'x':  # Only include if it's not 'x'
                        # Append to existing entry if there's a conflict
                        existing_entry = timetable_matrix.at[time_slot, day]
                        # Wrap subject in <b> tags for bold text
                        new_entry = f"<b>{subject} ({room_number})</b>"
                        if existing_entry:
                            timetable_matrix.at[time_slot, day] = existing_entry + "<br>" + new_entry
                        else:
                            timetable_matrix.at[time_slot, day] = new_entry

    # Fill the timetable matrix for core and elective timetables
    fill_timetable(core_timetable)
    fill_timetable(elective_1_timetable)
    fill_timetable(elective_2_timetable)

    # Replace NaN values with blank spaces
    timetable_matrix = timetable_matrix.fillna('')

    # Sort the table based on time slots
    timetable_matrix = timetable_matrix.reindex(times)

    return timetable_matrix

# Function to visualize the timetable using Plotly with selected color schemes and background image
def visualize_timetable(timetable_matrix):
    if timetable_matrix is None:
        return None

    # Create bold Time column by wrapping with <b> tags
    bold_time_slots = [f"<b>{time}</b>" for time in timetable_matrix.index]

    # Define the background image URL (Replace with a valid Taylor Swift image URL)
    background_image_url = "https://i.imgur.com/your_image.jpg"  # Replace with your image URL

    # Create the table
    fig = go.Figure(data=[go.Table(
        columnwidth = [100] + [120]*6,
        header=dict(
            values=['<b>TIME</b>'] + [f'<b>{day.upper()}</b>' for day in days],  # Days in uppercase
            fill_color=selected_scheme['header_fill'],
            align='center',
            font=dict(color=selected_scheme['header_text'], size=14, family='Arial Black'),
            height=50
        ),
        cells=dict(
            values=[bold_time_slots] + [timetable_matrix[day].tolist() for day in days],
            fill=dict(
                color=[
                    [selected_scheme['time_fill']] * len(times),  # Time column with selected fill color
                    *[
                        [selected_scheme['day_fill_1']] * len(times) if i % 2 == 0 else [selected_scheme['day_fill_2']] * len(times)
                        for i in range(len(days))
                    ]
                ]
            ),
            align='center',
            font=dict(
                color=[
                    selected_scheme['time_text']
                ] + [
                    [selected_scheme['day_text']] * len(times) for _ in days
                ],
                size=12,
                family='Arial'
            ),
            height=40,
            line_color='rgba(0,0,0,0.1)',
            line_width=1
        )
    )])

    # Add background image to the figure
    fig.update_layout(
        images=[dict(
            source=background_image_url,
            xref="paper", yref="paper",
            x=0, y=1,
            sizex=1, sizey=1,
            sizing="stretch",
            opacity=0.2,
            layer="below"
        )],
        title=dict(
            text='📅 Student Timetable',
            x=0.5,
            xanchor='center',
            font=dict(size=24, family='Arial Black', color='teal')
        ),
        margin=dict(l=20, r=20, t=60, b=20),
        height=700,
        paper_bgcolor='rgba(0,0,0,0)',  # Transparent paper background
        plot_bgcolor='rgba(0,0,0,0)',   # Transparent plot background
        font=dict(family='Arial')
    )

    return fig

# Function to save the timetable as an image
def save_timetable_as_image(fig, filename='timetable.jpg'):
    if fig is None:
        st.error("No figure to save.")
        return
    try:
        img_bytes = fig.to_image(format='jpg')
        return img_bytes
    except Exception as e:
        st.error(f"Error saving image: {e}")
        return None

# Function to display download button in Streamlit
def create_download_button(img_bytes, filename='timetable.jpg'):
    if not img_bytes:
        st.error("No image to download.")
        return
    st.download_button(
        label="📥 Download Timetable as JPG",
        data=img_bytes,
        file_name=filename,
        mime="image/jpg",
        key='download-button'
    )

# Main Streamlit App
def main():
    st.title("🎓 Student Timetable Viewer")

    # Display Taylor Swift logo or image at the top (optional)
    # Replace the URL below with your desired image URL
    logo_image_url = 'https://i.imgur.com/your_logo.png'  # Replace with your logo/image URL
    st.image(logo_image_url, width=600)  # Optional: Comment out if not needed

    # User input for Roll Number
    roll_number = st.text_input("Enter Your Roll Number", max_chars=10)

    # Checkbox for downloading timetable as JPG
    download = st.checkbox("Download timetable as JPG image")

    # Button to generate timetable
    if st.button("Generate Timetable"):
        if roll_number:
            timetable_df = generate_timetable_df(roll_number)
            if timetable_df is not None:
                fig = visualize_timetable(timetable_df)
                if fig:
                    st.plotly_chart(fig, use_container_width=True)
                    if download:
                        img_bytes = save_timetable_as_image(fig)
                        if img_bytes:
                            create_download_button(img_bytes)
        else:
            st.error("Please enter a valid roll number.")

    # Footer - Hide Streamlit's default footer
    hide_streamlit_style = """
                <style>
                footer {visibility: hidden;}
                </style>
                """
    st.markdown(hide_streamlit_style, unsafe_allow_html=True)

if __name__ == "__main__":
    main()